
  services:
    # PostgreSQL Database
    db:
      image: postgres:16
      restart: always
      env_file:
        - .env
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
        - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/01-init-db.sql
        - ../admin_utilities/create_rdms_user.sql:/docker-entrypoint-initdb.d/02-create-rdms-user.sql
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U db_user_service_user_api -d user_accounts_db"]
        interval: 5s
        timeout: 5s
        retries: 10

    # User Management API Service
    user_api:
      build: ./user_api
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - ./user_api:/app  # For development hot-reload
      ports:
        - "8000:8000"
      depends_on:
        db:
          condition: service_healthy
      env_file:
        - .env

  volumes:
    postgres_data:
